### ISSUE TITLE
Navigating with keyboard

### ISSUE THREAD

**Issue by zaunpfahl** [spectrafox/spectrafox#1]
Open folder by pressing return would be helpfull

**Comment by chemicha** [comment]
Will be included in the next version.
Thank you!

**Comment by chemicha** [comment]
In the next release there will be the possibility to navigate with the keyboard as well in the right folder content view in the folder browser.
- If you select a folder it gets opened when you press enter.
- If no folder is selected the current folder is opened in the data browser.
