### ISSUE TITLE
Feature Request: "Range Label" for x-Axis in Thumbnail 

### ISSUE THREAD

**Issue by zaunpfahl** [spectrafox/spectrafox#10]
For a faster browsing/finding of spectra it might be helpfull to know the Range of the x-Axis (i.e. for dZ/dV-Spectra, since they do not cross 0).

Possible Solutions:
show highest and lowest value of x-Axis next to the Axis-Label

**Comment by chemicha** [comment]
included in upcoming version

**Comment by chemicha** [comment]
Oh, I forgot:

please delete the cached preview images for all files for the ranges to appear in the images.

**Comment by zaunpfahl** [comment]
where can I do that?
