### ISSUE TITLE
Doctoral Error

### ISSUE THREAD

**Issue by zaunpfahl** [spectrafox/spectrafox#11]
This Error is reproducible by following steps:
1) open nanonis spectrum (dat-file) in data-browser
2) open same spectrum externally (e.g. Textpad)
3) delete first line in spectrum (e.g. "Experiment	 bias spectroscopy")
4) double click in data-browser on spectrum to open Spectroscopy Explorer
5) make screenshot of occuring error message
6) print out
7) glue onto graduation cap

**Comment by chemicha** [comment]
:-)))

Fixed in upcoming release.
