### ISSUE TITLE
Preview-Switch for browsing of spectra

### ISSUE THREAD

**Issue by zaunpfahl** [spectrafox/spectrafox#2]
For people just browsing through spectra and comparing different spectra it would be nice to have multiple spectra appearing in the preview by selecting them.

IDEA: a checkbox for auto-display
- unchecked: multiple selection are not automatically displayed (useful for datamanipulation etc)
- checked: multiple selection automatically displays all selected spectra for faster/easier comparison

**Comment by chemicha** [comment]
Thanks for the suggestion.
Will be included in the next release!
