### ISSUE TITLE
Fix z-channel in image display OR set default to preview-channel

### ISSUE THREAD

**Issue by zaunpfahl** [spectrafox/spectrafox#6]
When going through images, there are sometimes a couple of const. Height images for AFM or dI/dV map. Default is to display the z-channel, so one has to adjust that channel every time for every image.

IDEA 1: Couple default displayed channel to the preview-channel
IDEA 2: keep channel of previous image

**Comment by chemicha** [comment]
Thanks! Will be fixed in next release.
