### ISSUE TITLE
Number of Datapoints displayed in data-browser not correct

### ISSUE THREAD

**Issue by zaunpfahl** [spectrafox/spectrafox#8]
The value "data:" in the "data-browser" displays the number of datapoints for bias-spectroscopy, even if the recorded spectrum is a z-spectroscopy with different number of datapoints.

The number of points in the "Spectroscopy Explorer" seems to be correct.

SpectraFox Version: 2016.10.05.0 (from grouphome)

**Comment by chemicha** [comment]
Should be fixed in next version!
